server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wts-auth?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: skanushka
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: always
